# Generated by Django 5.2.5 on 2025-10-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('notebook', 'Notebook')], default='desktop', max_length=10, verbose_name='Tipo de Dispositivo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('service_tag', models.CharField(max_length=100, unique=True, verbose_name='Service Tag')),
                ('processor', models.CharField(max_length=100, verbose_name='Processador')),
                ('ram', models.CharField(max_length=50, verbose_name='Memória RAM')),
                ('ssd', models.CharField(max_length=50, verbose_name='SSD/Armazenamento')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
    ]
