# Generated by Django 5.2.5 on 2025-10-03 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome / Razão Social')),
                ('document', models.CharField(max_length=50, unique=True, verbose_name='CPF/CNPJ')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contato')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('locacao', 'Nova Locação'), ('aditivo', 'Aditivo'), ('devolucao', 'Devolução'), ('manutencao', 'Manutenção'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('movement_date', models.DateField(verbose_name='Data da Movimentação')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalhes/Observação')),
                ('issue_description', models.TextField(verbose_name='Descrição do Problema')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Movimentação')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.client', verbose_name='Cliente')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
    ]
