# Generated by Django 5.2.5 on 2025-10-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_client_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Marcar como produto novo'),
        ),
    ]
