# Generated by Django 5.2.5 on 2025-10-03 15:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_device_is_new'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Marcar como novo'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='movement_type',
            field=models.CharField(choices=[('locacao', 'Nova Locação'), ('aditivo', 'Aditivo'), ('devolucao', 'Devolução'), ('manutencao', 'Manutenção'), ('venda', 'Venda'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Movimentação'),
        ),
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('notebook', 'Notebook')], default='desktop', max_length=10, verbose_name='Tipo de Dispositivo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('service_tag', models.CharField(db_index=True, max_length=100, verbose_name='Service Tag')),
                ('processor', models.CharField(max_length=100, verbose_name='Processador')),
                ('ram', models.CharField(max_length=50, verbose_name='Memória RAM')),
                ('ssd', models.CharField(max_length=50, verbose_name='SSD/Armazenamento')),
                ('is_new', models.BooleanField(default=False, verbose_name='Marcar como novo')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Cadastro')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Dispositivo',
                'verbose_name_plural': 'historical Dispositivos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
