# Generated by Django 5.2.5 on 2025-10-03 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_device_is_new_alter_movimentacao_movement_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Inspeção')),
                ('physical_state', models.CharField(choices=[('uso', 'Com marcas de uso'), ('riscos', 'Riscos profundos'), ('outros', 'Outros')], max_length=10, verbose_name='Estado Físico')),
                ('physical_state_other', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outro Estado Físico')),
                ('has_charger', models.BooleanField(verbose_name='Possui Carregador?')),
                ('charger_condition', models.CharField(blank=True, choices=[('usado', 'Usado'), ('novo', 'Novo')], max_length=10, null=True, verbose_name='Condição do Carregador')),
                ('configuration', models.CharField(choices=[('conforme', 'Conforme'), ('modificado', 'Modificado')], max_length=10, verbose_name='Configurações')),
                ('configuration_mods', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modificações')),
                ('os_installed', models.BooleanField(verbose_name='Sistema Operacional Instalado?')),
                ('has_office', models.BooleanField(verbose_name='Possui Office?')),
                ('office_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Versão do Office')),
                ('office_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave do Office')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Adicionais')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Inspeção',
                'verbose_name_plural': 'Inspeções',
                'ordering': ['-inspection_date'],
            },
        ),
    ]
